nodeLinker: node-modules

packageExtensions:
  "@chromatic-com/storybook@3.2.6":
    peerDependencies:
      react: "*"
  "@storybook/addon-docs@8.6.14":
    peerDependencies:
      "@types/react": "*"
  "@storybook/addon-essentials@8.6.14":
    peerDependencies:
      "@types/react": "*"
  "@storybook/core@8.6.14":
    peerDependencies:
      storybook: "*"
  "@storybook/experimental-addon-test@8.6.14":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/react-vite@8.6.14":
    peerDependencies:
      typescript: "*"
  eslint-plugin-storybook@0.12.0:
    peerDependencies:
      typescript: "*"

yarnPath: .yarn/releases/yarn-4.9.4.cjs
