FROM tipa_frontend_react:latest AS builder

FROM nginx:1.17
#RUN apt-get update && apt-get install -y vim
RUN rm -rf /etc/nginx/conf.d/*.conf

#COPY ./conf/server.conf /etc/nginx/conf.d/
RUN apt-get update && apt-get install -y vim && apt-get install -y net-tools && apt-get install -y curl
RUN rm -rf /etc/nginx/nginx.conf
COPY ./conf/nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /usr/share/nginx/html /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
