export interface ButtonStyles {
  borderColor: string;
  borderWidth: number;
  borderRadius: string;
  paddingX: number;
  paddingY: number;
  fontSize: number;
  fontWeight: string;
  textTransform: "none" | "uppercase" | "lowercase" | "capitalize";
  letterSpacing: number;
  lineHeight: number;
  shadowOpacity: number;
  shadowColor: string;
  shadowOffsetX: number;
  shadowOffsetY: number;
  shadowBlur: number;
  shadowSpread: number;
  hoverBackgroundColor: string;
  hoverBackgroundOpacity: number;
  hoverTextColor: string;
  hoverBorderColor: string;
  focusBorderColor: string;
  focusRingColor: string;
  focusRingWidth: number;
  activeBackgroundColor: string;
  activeTextColor: string;
  activeBorderColor: string;
  transitionDuration: number;
  transitionEasing: string;
}
