import type { Metadata } from 'next'

import './index.css'

import React from 'react'
import localFont from 'next/font/local'
import { StoreProvider } from '@/global/redux/StoreProvider'
import QueryProvider from '@/global/tanstackQuery/QueryProvider'
import { ToastContainer } from 'react-toastify'

//폰트 추가
const pretendard = localFont({
    src: '../assets/fonts/PretendardVariable.woff2',
    display: 'swap',
    weight: '45 920',
    variable: '--font-pretendard',
})

//메타 데이터 추가
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={` ${pretendard.variable} antialiased`}>
                <QueryProvider>
                    <StoreProvider>
                        {children}
                        <ToastContainer />
                    </StoreProvider>
                </QueryProvider>
            </body>
        </html>
    )
}
